version: "3.9"

services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats: 
    image: nats:alpine
    hostname: nats
    ports:
      - 4222:4222
      - 8222:8222
    command:
      - -js
      - -sd
      - /var/lib/nats/data
    healthcheck:
      test: ["CMD", "nats-server", "-sl"]
      interval: 5s
      timeout: 5s
      retries: 5
